// This file is auto-generated by @hey-api/openapi-ts

export const TodoDTOSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            format: 'int32'
        },
        name: {
            type: 'string',
            nullable: true
        },
        number: {
            type: 'integer',
            format: 'int32'
        }
    },
    additionalProperties: false
} as const;