// This file is auto-generated by @hey-api/openapi-ts

export const CreateSubTaskRequestSchema = {
    type: 'object',
    properties: {
        taskId: {
            type: 'integer',
            format: 'int32'
        },
        subTaskName: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const CreateTaskRequestSchema = {
    type: 'object',
    properties: {
        todoListId: {
            type: 'integer',
            format: 'int32'
        },
        taskName: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const CreateTodoListRequestSchema = {
    type: 'object',
    properties: {
        userId: {
            type: 'integer',
            format: 'int32'
        },
        listName: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const CreateUserRequestSchema = {
    type: 'object',
    properties: {
        username: {
            type: 'string',
            nullable: true
        },
        password: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const SubTaskDBOSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            format: 'int32'
        },
        subTaskName: {
            type: 'string',
            nullable: true
        },
        taskId: {
            type: 'integer',
            format: 'int32'
        }
    },
    additionalProperties: false
} as const;

export const TaskDBOSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            format: 'int32'
        },
        taskName: {
            type: 'string',
            nullable: true
        },
        todoListId: {
            type: 'integer',
            format: 'int32'
        },
        subTasks: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/SubTaskDBO'
            },
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const TodoListDBOSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            format: 'int32'
        },
        listName: {
            type: 'string',
            nullable: true
        },
        userId: {
            type: 'integer',
            format: 'int32'
        },
        tasks: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/TaskDBO'
            },
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const TodoListObjectSchema = {
    type: 'object',
    properties: {
        mainItem: {
            type: 'string',
            nullable: true
        },
        taskId: {
            type: 'integer',
            format: 'int64'
        },
        subItemList: {
            type: 'array',
            items: {
                type: 'string'
            },
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const TodoListObjectDTOSchema = {
    type: 'object',
    properties: {
        listName: {
            type: 'string',
            nullable: true
        },
        listId: {
            type: 'integer',
            format: 'int64'
        },
        todoListObject: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/TodoListObject'
            },
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const UserDBOSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            format: 'int32'
        },
        salt: {
            type: 'string',
            nullable: true
        },
        username: {
            type: 'string',
            nullable: true
        },
        hashedPassword: {
            type: 'string',
            nullable: true
        },
        todoLists: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/TodoListDBO'
            },
            nullable: true
        }
    },
    additionalProperties: false
} as const;