// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { GetUserInputData, GetUserInputError, GetUserInputResponse, GetUserUsernameData, GetUserUsernameError, GetUserUsernameResponse, GetUserByIdData, GetUserByIdError, GetUserByIdResponse, GetUserDataByIdData, GetUserDataByIdError, GetUserDataByIdResponse, PostUserData, PostUserError, PostUserResponse, PostUserTodoListData, PostUserTodoListError, PostUserTodoListResponse, DeleteUserTodoListByIdData, DeleteUserTodoListByIdError, DeleteUserTodoListByIdResponse, PostUserTodoListTaskData, PostUserTodoListTaskError, PostUserTodoListTaskResponse, DeleteUserTodoListTaskByIdData, DeleteUserTodoListTaskByIdError, DeleteUserTodoListTaskByIdResponse, PostUserTodoListTaskSubtaskData, PostUserTodoListTaskSubtaskError, PostUserTodoListTaskSubtaskResponse } from './types.gen';

export const client = createClient(createConfig());

export const getUserInput = <ThrowOnError extends boolean = false>(options: Options<GetUserInputData, ThrowOnError>) => { return (options?.client ?? client).get<GetUserInputResponse, GetUserInputError, ThrowOnError>({
    ...options,
    url: '/user/input'
}); };

export const getUserUsername = <ThrowOnError extends boolean = false>(options: Options<GetUserUsernameData, ThrowOnError>) => { return (options?.client ?? client).get<GetUserUsernameResponse, GetUserUsernameError, ThrowOnError>({
    ...options,
    url: '/user/username'
}); };

export const getUserById = <ThrowOnError extends boolean = false>(options: Options<GetUserByIdData, ThrowOnError>) => { return (options?.client ?? client).get<GetUserByIdResponse, GetUserByIdError, ThrowOnError>({
    ...options,
    url: '/user/{id}'
}); };

export const getUserDataById = <ThrowOnError extends boolean = false>(options: Options<GetUserDataByIdData, ThrowOnError>) => { return (options?.client ?? client).get<GetUserDataByIdResponse, GetUserDataByIdError, ThrowOnError>({
    ...options,
    url: '/user/data/{id}'
}); };

export const postUser = <ThrowOnError extends boolean = false>(options: Options<PostUserData, ThrowOnError>) => { return (options?.client ?? client).post<PostUserResponse, PostUserError, ThrowOnError>({
    ...options,
    url: '/user'
}); };

export const postUserTodoList = <ThrowOnError extends boolean = false>(options: Options<PostUserTodoListData, ThrowOnError>) => { return (options?.client ?? client).post<PostUserTodoListResponse, PostUserTodoListError, ThrowOnError>({
    ...options,
    url: '/user/todoList'
}); };

export const deleteUserTodoListById = <ThrowOnError extends boolean = false>(options: Options<DeleteUserTodoListByIdData, ThrowOnError>) => { return (options?.client ?? client).delete<DeleteUserTodoListByIdResponse, DeleteUserTodoListByIdError, ThrowOnError>({
    ...options,
    url: '/user/todoList/{id}'
}); };

export const postUserTodoListTask = <ThrowOnError extends boolean = false>(options: Options<PostUserTodoListTaskData, ThrowOnError>) => { return (options?.client ?? client).post<PostUserTodoListTaskResponse, PostUserTodoListTaskError, ThrowOnError>({
    ...options,
    url: '/user/todoList/task'
}); };

export const deleteUserTodoListTaskById = <ThrowOnError extends boolean = false>(options: Options<DeleteUserTodoListTaskByIdData, ThrowOnError>) => { return (options?.client ?? client).delete<DeleteUserTodoListTaskByIdResponse, DeleteUserTodoListTaskByIdError, ThrowOnError>({
    ...options,
    url: '/user/todoList/task/{id}'
}); };

export const postUserTodoListTaskSubtask = <ThrowOnError extends boolean = false>(options: Options<PostUserTodoListTaskSubtaskData, ThrowOnError>) => { return (options?.client ?? client).post<PostUserTodoListTaskSubtaskResponse, PostUserTodoListTaskSubtaskError, ThrowOnError>({
    ...options,
    url: '/user/todoList/task/subtask'
}); };