// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { GetTodosError, GetTodosResponse, GetTodosByIdData, GetTodosByIdError, GetTodosByIdResponse } from './types.gen';

export const client = createClient(createConfig());

export const getTodos = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).get<GetTodosResponse, GetTodosError, ThrowOnError>({
    ...options,
    url: '/todos'
}); };

export const getTodosById = <ThrowOnError extends boolean = false>(options: Options<GetTodosByIdData, ThrowOnError>) => { return (options?.client ?? client).get<GetTodosByIdResponse, GetTodosByIdError, ThrowOnError>({
    ...options,
    url: '/todos/{id}'
}); };