// This file is auto-generated by @hey-api/openapi-ts

export type CreateSubTaskRequest = {
    taskId?: number;
    subTaskName?: (string) | null;
};

export type CreateTaskRequest = {
    todoListId?: number;
    taskName?: (string) | null;
};

export type CreateTodoListRequest = {
    userId?: number;
    listName?: (string) | null;
};

export type CreateUserRequest = {
    username?: (string) | null;
    password?: (string) | null;
};

export type TodoListObject = {
    mainItem?: (string) | null;
    taskId?: number;
    subItemList?: Array<(string)> | null;
};

export type TodoListObjectDTO = {
    listName?: (string) | null;
    listId?: number;
    todoListObject?: Array<TodoListObject> | null;
};

export type GetUserInputData = {
    query: {
        Password: string;
        Username: string;
    };
};

export type GetUserInputResponse = (unknown);

export type GetUserInputError = unknown;

export type GetUserInputUsernameData = {
    query: {
        Username: string;
    };
};

export type GetUserInputUsernameResponse = (unknown);

export type GetUserInputUsernameError = unknown;

export type GetUserByIdData = {
    path: {
        id: number;
    };
};

export type GetUserByIdResponse = (unknown);

export type GetUserByIdError = unknown;

export type GetUserDataByIdData = {
    path: {
        id: number;
    };
};

export type GetUserDataByIdResponse = (Array<TodoListObjectDTO>);

export type GetUserDataByIdError = unknown;

export type PostUserData = {
    body: CreateUserRequest;
};

export type PostUserResponse = (unknown);

export type PostUserError = unknown;

export type PostUserTodoListData = {
    body: CreateTodoListRequest;
};

export type PostUserTodoListResponse = (unknown);

export type PostUserTodoListError = unknown;

export type DeleteUserTodoListByIdData = {
    path: {
        id: number;
    };
};

export type DeleteUserTodoListByIdResponse = (unknown);

export type DeleteUserTodoListByIdError = unknown;

export type PostUserTodoListTaskData = {
    body: CreateTaskRequest;
};

export type PostUserTodoListTaskResponse = (unknown);

export type PostUserTodoListTaskError = unknown;

export type DeleteUserTodoListTaskByIdData = {
    path: {
        id: number;
    };
};

export type DeleteUserTodoListTaskByIdResponse = (unknown);

export type DeleteUserTodoListTaskByIdError = unknown;

export type PostUserTodoListTaskSubtaskData = {
    body: CreateSubTaskRequest;
};

export type PostUserTodoListTaskSubtaskResponse = (unknown);

export type PostUserTodoListTaskSubtaskError = unknown;