// This file is auto-generated by @hey-api/openapi-ts

export type CreateSubTaskRequest = {
    taskId?: number;
    subTaskName?: (string) | null;
};

export type CreateTaskRequest = {
    todoListId?: number;
    taskName?: (string) | null;
};

export type CreateTodoListRequest = {
    userId?: number;
    listName?: (string) | null;
};

export type CreateUserRequest = {
    username?: (string) | null;
    password?: (string) | null;
};

export type SubTaskDTO = {
    id?: number;
    taskId?: number;
    subTaskName?: (string) | null;
};

export type TaskDTO = {
    id?: number;
    todoListId?: number;
    taskName?: (string) | null;
};

export type TodoListDTO = {
    id?: number;
    userId?: number;
    listName?: (string) | null;
};

export type TodoListObject = {
    mainItem?: (string) | null;
    taskId?: number;
    subItemList?: Array<(string)> | null;
};

export type TodoListObjectDTO = {
    listName?: (string) | null;
    listId?: number;
    todoListObject?: Array<TodoListObject> | null;
};

export type UserDTO = {
    id?: number;
    username?: (string) | null;
    password?: (string) | null;
};

export type GetByIdData = {
    path: {
        id: number;
    };
};

export type GetByIdResponse = (Array<TodoListObjectDTO>);

export type GetByIdError = unknown;

export type PutUserByIdData = {
    body: UserDTO;
    path: {
        id: number;
    };
};

export type PutUserByIdResponse = (unknown);

export type PutUserByIdError = unknown;

export type DeleteUserByIdData = {
    path: {
        id: number;
    };
};

export type DeleteUserByIdResponse = (unknown);

export type DeleteUserByIdError = unknown;

export type PostUserData = {
    body: CreateUserRequest;
};

export type PostUserResponse = (unknown);

export type PostUserError = unknown;

export type PutUserTodoListByIdData = {
    body: TodoListDTO;
    path: {
        id: number;
    };
};

export type PutUserTodoListByIdResponse = (unknown);

export type PutUserTodoListByIdError = unknown;

export type DeleteUserTodoListByIdData = {
    path: {
        id: number;
    };
};

export type DeleteUserTodoListByIdResponse = (unknown);

export type DeleteUserTodoListByIdError = unknown;

export type PostUserTodoListData = {
    body: CreateTodoListRequest;
};

export type PostUserTodoListResponse = (unknown);

export type PostUserTodoListError = unknown;

export type PutUserTodoListTaskByIdData = {
    body: TaskDTO;
    path: {
        id: number;
    };
};

export type PutUserTodoListTaskByIdResponse = (unknown);

export type PutUserTodoListTaskByIdError = unknown;

export type DeleteUserTodoListTaskByIdData = {
    path: {
        id: number;
    };
};

export type DeleteUserTodoListTaskByIdResponse = (unknown);

export type DeleteUserTodoListTaskByIdError = unknown;

export type PostUserTodoListTaskData = {
    body: CreateTaskRequest;
};

export type PostUserTodoListTaskResponse = (unknown);

export type PostUserTodoListTaskError = unknown;

export type PutUserTodoListTaskSubtaskByIdData = {
    body: SubTaskDTO;
    path: {
        id: number;
    };
};

export type PutUserTodoListTaskSubtaskByIdResponse = (unknown);

export type PutUserTodoListTaskSubtaskByIdError = unknown;

export type DeleteUserTodoListTaskSubtaskByIdData = {
    path: {
        id: number;
    };
};

export type DeleteUserTodoListTaskSubtaskByIdResponse = (unknown);

export type DeleteUserTodoListTaskSubtaskByIdError = unknown;

export type PostUserTodoListTaskSubtaskData = {
    body: CreateSubTaskRequest;
};

export type PostUserTodoListTaskSubtaskResponse = (unknown);

export type PostUserTodoListTaskSubtaskError = unknown;