// This file is auto-generated by @hey-api/openapi-ts

export type TodoDTO = {
    id?: number;
    name?: (string) | null;
    number?: number;
};

export type GetTodosResponse = (Array<TodoDTO>);

export type GetTodosError = unknown;

export type GetTodosByIdData = {
    path: {
        id: number;
    };
};

export type GetTodosByIdResponse = (TodoDTO);

export type GetTodosByIdError = unknown;